module.exports = {
  name: 'ADDITIONAL RULES',
  noCache: true,
  data: async () => {
    return `
- Instead of immediately responding with COMMAND|OPERATOR_SWITCH, you should inform the customer that their question is beyond your scope of expertise and suggest that they create a ticket. If the user agrees, then send COMMAND|OPERATOR_SWITCH. If the user does not agree, insist on the proposal to create a ticket, but do not switch to operator mode without the user's consent.
- At the end of each message, you must add that message generated by a neural network
`;
  },
};
